import type {
  User,
  Company,
  CarrierProfile,
  Vehicle,
  ReturnRoute,
  ShipmentRequest,
  Match,
  TrackingEvent,
  Rating,
  Notification,
} from "./types";

export const seedUsers: User[] = [
  {
    id: "u-1",
    email: "logistica@grupobimsa.com.mx",
    name: "Ricardo Hernández",
    phone: "555-1234",
    role: "embarcador",
    verificationStatus: "approved",
    createdAt: "2024-11-01T10:00:00Z",
    onboardingCompleted: true,
    avatarUrl: undefined,
  },
  {
    id: "u-2",
    email: "operaciones@transportesramirez.mx",
    name: "Carlos Ramírez",
    phone: "555-5678",
    role: "transportista",
    verificationStatus: "approved",
    createdAt: "2024-10-15T08:00:00Z",
    onboardingCompleted: true,
    avatarUrl: undefined,
  },
  {
    id: "u-3",
    email: "admin@zzingrush.mx",
    name: "Admin ZzingRush",
    role: "admin",
    verificationStatus: "approved",
    createdAt: "2024-09-01T00:00:00Z",
    onboardingCompleted: true,
  },
];

export const seedCompanies: Company[] = [
  {
    id: "c-1",
    userId: "u-1",
    legalName: "Grupo BIMSA S.A. de C.V.",
    tradeName: "BIMSA",
    rfc: "GBI9901154S3",
    address: "Av. Insurgentes Sur 1443",
    city: "Ciudad de México",
    state: "CDMX",
    postalCode: "03920",
    industry: "Manufactura / Alimentos",
    verificationStatus: "approved",
    createdAt: "2024-11-01T10:00:00Z",
  },
  {
    id: "c-2",
    userId: "u-2",
    legalName: "Transportes Ramírez e Hijos S.A. de C.V.",
    tradeName: "Trans Ramírez",
    rfc: "TRH010823AB1",
    address: "Blvd. Aeropuerto 2240",
    city: "Guadalajara",
    state: "Jalisco",
    postalCode: "44940",
    industry: "Transporte de carga",
    verificationStatus: "approved",
    createdAt: "2024-10-15T08:00:00Z",
  },
];

export const seedCarrierProfiles: CarrierProfile[] = [
  {
    id: "cp-1",
    userId: "u-2",
    companyId: "c-2",
    operatorType: "empresa",
    licenseNumber: "LIC-JAL-88432",
    operatingStates: ["Jalisco", "CDMX", "Nuevo León", "Guanajuato"],
    specialties: ["carga general", "manufactura", "alimentos no perecederos"],
    totalTrips: 142,
    onTimeRate: 96.5,
    claimRate: 0.7,
    avgRating: 4.8,
    reputationTier: "elite",
    verificationStatus: "approved",
  },
];

export const seedVehicles: Vehicle[] = [
  {
    id: "v-1",
    carrierId: "cp-1",
    type: "torton",
    brand: "International",
    model: "ProStar",
    year: 2021,
    plates: "JLA-123-B",
    capacityKg: 18000,
    capacityM3: 90,
    hasRefrigeration: false,
    verificationStatus: "approved",
    insuranceExpiry: "2025-08-31",
    documentIds: ["doc-1", "doc-2"],
  },
  {
    id: "v-2",
    carrierId: "cp-1",
    type: "rabon",
    brand: "Kenworth",
    model: "T370",
    year: 2019,
    plates: "JLC-556-D",
    capacityKg: 10000,
    capacityM3: 55,
    hasRefrigeration: false,
    verificationStatus: "approved",
    insuranceExpiry: "2025-06-30",
    documentIds: ["doc-3"],
  },
];

export const seedRoutes: ReturnRoute[] = [
  {
    id: "r-1",
    carrierId: "cp-1",
    vehicleId: "v-1",
    originCity: "Monterrey",
    originState: "Nuevo León",
    destinationCity: "Ciudad de México",
    destinationState: "CDMX",
    departureDateFrom: "2025-02-10",
    departureDateTo: "2025-02-11",
    availableCapacityKg: 14000,
    availableCapacityM3: 70,
    pricePerKm: 12.5,
    estimatedDistance: 938,
    acceptedCargoTypes: ["carga general", "manufactura", "papel", "electrodomésticos"],
    status: "published",
    potentialEarnings: 11725,
    createdAt: "2025-02-05T14:00:00Z",
  },
  {
    id: "r-2",
    carrierId: "cp-1",
    vehicleId: "v-2",
    originCity: "Guadalajara",
    originState: "Jalisco",
    destinationCity: "Querétaro",
    destinationState: "Querétaro",
    departureDateFrom: "2025-02-14",
    departureDateTo: "2025-02-14",
    availableCapacityKg: 8000,
    availableCapacityM3: 40,
    pricePerKm: 11,
    estimatedDistance: 260,
    acceptedCargoTypes: ["carga general", "alimentos no perecederos", "textiles"],
    status: "matched",
    potentialEarnings: 2860,
    createdAt: "2025-02-06T09:00:00Z",
  },
];

export const seedShipments: ShipmentRequest[] = [
  {
    id: "s-1",
    shipperId: "u-1",
    originCity: "Monterrey",
    originState: "Nuevo León",
    destinationCity: "Ciudad de México",
    destinationState: "CDMX",
    cargoDescription: "Electrodomésticos — refrigeradores y lavadoras en pallets",
    cargoType: "electrodomésticos",
    weightKg: 12000,
    volumeM3: 60,
    requiredDate: "2025-02-11",
    isFragile: false,
    requiresRefrigeration: false,
    declaredValue: 850000,
    status: "matched",
    estimatedPrice: 10500,
    createdAt: "2025-02-05T16:00:00Z",
  },
  {
    id: "s-2",
    shipperId: "u-1",
    originCity: "Ciudad de México",
    originState: "CDMX",
    destinationCity: "Guadalajara",
    destinationState: "Jalisco",
    cargoDescription: "Materiales de empaque — cajas de cartón corrugado",
    cargoType: "materiales de empaque",
    weightKg: 5500,
    volumeM3: 28,
    requiredDate: "2025-02-18",
    isFragile: false,
    requiresRefrigeration: false,
    declaredValue: 120000,
    status: "published",
    estimatedPrice: 4200,
    createdAt: "2025-02-07T11:00:00Z",
  },
  {
    id: "s-3",
    shipperId: "u-1",
    originCity: "Querétaro",
    originState: "Querétaro",
    destinationCity: "Monterrey",
    destinationState: "Nuevo León",
    cargoDescription: "Autopartes — piezas metálicas en cajas estibadas",
    cargoType: "autopartes",
    weightKg: 9000,
    volumeM3: 35,
    requiredDate: "2025-02-20",
    isFragile: false,
    requiresRefrigeration: false,
    declaredValue: 460000,
    status: "in_transit",
    estimatedPrice: 7800,
    createdAt: "2025-02-01T09:00:00Z",
  },
];

export const seedMatches: Match[] = [
  {
    id: "m-1",
    shipmentId: "s-1",
    routeId: "r-1",
    carrierId: "cp-1",
    shipperId: "u-1",
    matchScore: 94,
    detourKm: 18,
    estimatedPrice: 10500,
    carrierEarnings: 9345,
    shipperSavings: 3200,
    status: "accepted",
    expiresAt: "2025-02-08T23:59:00Z",
    createdAt: "2025-02-06T10:00:00Z",
  },
];

export const seedTrackingEvents: TrackingEvent[] = [
  {
    id: "te-1",
    shipmentId: "s-3",
    eventType: "escrow_funded",
    city: "Querétaro",
    state: "Querétaro",
    notes: "Fondos recibidos en custodia. Transportista notificado.",
    reportedBy: "system",
    createdAt: "2025-02-01T10:00:00Z",
  },
  {
    id: "te-2",
    shipmentId: "s-3",
    eventType: "carrier_confirmed",
    city: "Querétaro",
    state: "Querétaro",
    notes: "Transportista confirmó la recolección.",
    reportedBy: "u-2",
    createdAt: "2025-02-01T14:00:00Z",
  },
  {
    id: "te-3",
    shipmentId: "s-3",
    eventType: "pickup_completed",
    city: "Querétaro",
    state: "Querétaro",
    lat: 20.5888,
    lng: -100.3899,
    notes: "Carga recogida. Evidencia fotográfica registrada.",
    reportedBy: "u-2",
    createdAt: "2025-02-02T08:30:00Z",
  },
  {
    id: "te-4",
    shipmentId: "s-3",
    eventType: "in_transit",
    city: "San Luis Potosí",
    state: "San Luis Potosí",
    lat: 22.1565,
    lng: -100.9855,
    notes: "En tránsito. Última posición: San Luis Potosí.",
    reportedBy: "system",
    createdAt: "2025-02-02T14:15:00Z",
  },
];

export const seedRatings: Rating[] = [
  {
    id: "rat-1",
    shipmentId: "s-3",
    reviewerId: "u-1",
    revieweeId: "u-2",
    reviewerRole: "embarcador",
    overall: 5,
    punctuality: 5,
    communication: 5,
    documentation: 4,
    cargoCondition: 5,
    comment: "Excelente servicio. Llegó a tiempo, documentación en orden y la carga llegó sin daños.",
    createdAt: "2025-02-05T10:00:00Z",
  },
];

export const seedNotifications: Notification[] = [
  {
    id: "n-1",
    userId: "u-1",
    type: "match_found",
    title: "Coincidencia encontrada",
    body: "Encontramos una ruta de retorno compatible para tu envío MTY → CDMX.",
    read: false,
    link: "/app/embarcador/coincidencias/m-1",
    createdAt: "2025-02-06T10:01:00Z",
  },
  {
    id: "n-2",
    userId: "u-1",
    type: "escrow_funded",
    title: "Pago en custodia",
    body: "El monto de $7,800 MXN está reservado para el envío QRO → MTY.",
    read: true,
    link: "/app/embarcador/pago/s-3",
    createdAt: "2025-02-01T10:05:00Z",
  },
  {
    id: "n-3",
    userId: "u-2",
    type: "match_found",
    title: "Nueva carga disponible",
    body: "Hay una carga compatible con tu ruta de retorno MTY → CDMX.",
    read: false,
    link: "/app/transportista/coincidencias/m-1",
    createdAt: "2025-02-06T10:01:00Z",
  },
];
